before_script:

test_job:
  image: trion/ng-cli-karma
  stage: test
  tags:
    - linux
    - docker
  script:
    - npm install
    - ng lint --type-check true
    - ng test --no-progress --sr --cc
  artifacts:
    paths:
      - coverage/
pages:
  stage: deploy
  dependencies:
    - test_job
  script:
    - mv coverage/ public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - develop