before_script:
  - npm install

tslint_job:
  image: trion/ng-cli
  stage: test
  tags:
    - linux
    - docker
  script:
    - ng lint --type-check true

test_job:
  image: trion/ng-cli-karma
  stage: test
  tags:
    - linux
    - angular
    - angular material 2
  script:
    - ng test --no-progress --sr --cc
    - ./node_modules/.bin/codecov
