language: node_js
node_js:
  - "6"

dist: trusty
sudo: false

addons:
  apt:
    packages:
      - google-chrome-stable

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - npm install -g npm@5
  - npm install -g greenkeeper-lockfile@1
  - npm -v
  - npm install -g @angular/cli

branches:
  only:
    - master
    - develop
    - /^greenkeeper/.*$/
    - /^feature/.*$/
    - /^release/.*$/
    - /^hotfix/.*$/
    - codecovTest

before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
  
script:
  - ng lint --type-check
  - ng test --no-progress -sr -cc

after_success:
  - ./node_modules/.bin/codecov

notifications:
  email:
    on_failure: change
    on_success: change
