language: node_js
node_js:
  - "8"

dist: trusty
sudo: false

# addons:
#   apt:
#     packages:
#       - google-chrome-stable

# cache node modules for faster testing
cache:
  yarn: true
  directories:
     - ./node_modules


before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
#  - npm install -g npm@5
#  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost & 
  - yarn global add greenkeeper-lockfile@1
#  - npm -v
  - yarn global add @angular/cli

install: travis_retry

branches:
  only:
    - master
    - develop
    - /^greenkeeper/.*$/
    - /^feature/.*$/
    - /^release/.*$/
    - /^hotfix/.*$/
    - codecovTest

before_script: 
  - greenkeeper-lockfile-update
after_script: 
  - greenkeeper-lockfile-upload

script:
  - ng lint --type-check
  - ng test --no-progress -sr -cc

after_success:
  - ./node_modules/.bin/codecov

notifications:
  email:
    on_failure: change
    on_success: change
